# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# user specific environment
GEMHOME="$HOME/.gem"; export GEMHOME
GOPATH="$HOME/.go"; export GOPATH

alias msync='rsync -rltpuzP'
alias ssh-keygen='ssh-keygen -t ed25519 -a 100'

# user specific PATH
pathlist=(
    "$HOME/.local/bin"
    "$HOME/bin"
    "$GEMHOME/bin"
    "$GOPATH/bin"
)

for path in "${pathlist[@]}"; do
    if ! [[ ":$PATH:" == *":$path:"* ]]; then
        PATH="$path:$PATH"
        export PATH
    fi
done

unset path
unset pathlist

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
	for rc in ~/.bashrc.d/*; do
		if [ -f "$rc" ]; then
			. "$rc"
		fi
	done
fi

unset rc
